name: matrix-demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [20,22,24]
        operating-system: [ubuntu-latest,windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: build 
        run: npm run build


       